import React,{useEffect,useState} from 'react';import{createRoot}from'react-dom/client';import'./style.css';
const API='http://localhost:8000/api';
function App(){const[sessions,setSessions]=useState([]),[sid,setSid]=useState(null),[msgs,setMsgs]=useState([]),[input,setInput]=useState(''),[running,setRunning]=useState(false),[run,setRun]=useState(null),[approval,setApproval]=useState(null),[events,setEvents]=useState([]);
 const load=async()=>{let x=await fetch(API+'/sessions').then(r=>r.json());setSessions(x);if(!sid&&x[0])setSid(x[0].id)};useEffect(()=>{load()},[]);useEffect(()=>{if(sid)fetch(API+`/sessions/${sid}/messages`).then(r=>r.json()).then(setMsgs)},[sid]);
 async function newSession(){let s=await fetch(API+'/sessions',{method:'POST'}).then(r=>r.json());setSessions(x=>[s,...x]);setSid(s.id);setMsgs([])}
 async function send(){if(!input.trim()||running||!sid)return;let text=input;setInput('');setRunning(true);setEvents([]);let r=await fetch(API+`/sessions/${sid}/chat`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:text})});let reader=r.body.getReader(),dec=new TextDecoder(),buf='';while(true){let z=await reader.read();if(z.done)break;buf+=dec.decode(z.value);let parts=buf.split('\n\n');buf=parts.pop();for(let p of parts){if(!p.startsWith('data: '))continue;let e=JSON.parse(p.slice(6));setEvents(v=>[...v,e]);if(e.run_id)setRun(e.run_id);if(e.type==='approval_required')setApproval(e);if(e.type==='assistant_delta')setMsgs(v=>[...v,{role:'assistant',content:e.content}]);if(e.type==='done'){setRunning(false);setRun(null);fetch(API+`/sessions/${sid}/messages`).then(r=>r.json()).then(setMsgs)}}}}
 async function approve(action){if(!approval)return;await fetch(API+`/approvals/${approval.approval_id}?action=${action}`,{method:'POST'});setApproval(null)}
 async function cancel(){if(run)await fetch(API+`/runs/${run}/cancel`,{method:'POST'})}
 return <div className="app"><aside><h2>Harness</h2><button onClick={newSession}>+ New session</button>{sessions.map(s=><button className={s.id===sid?'sel':''} onClick={()=>setSid(s.id)} key={s.id}>{s.title} <small>{s.status}</small></button>)}</aside><main><header><b>Personal Harness Agent</b><span>{running?'● Running':'● Idle'}</span></header><section className="chat">{msgs.map((m,i)=><div className={'msg '+m.role} key={i}><b>{m.role}</b><div>{m.content}</div></div>)}{events.filter(e=>e.type.startsWith('tool_')).map((e,i)=><div className="event" key={i}>{e.type}: {e.tool||e.status||e.data||e.error||''}</div>)}</section>{approval&&<div className="approval"><b>Approval required</b><p>{approval.reason}</p><code>{approval.arguments?.command}</code><div><button onClick={()=>approve('approve')}>Approve</button><button onClick={()=>approve('reject')}>Reject</button></div></div>}<footer><input value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send()} placeholder="Ask your harness..."/><button onClick={send} disabled={running}>Send</button>{running&&<button onClick={cancel}>Cancel</button>}</footer></main></div>}
createRoot(document.getElementById('root')).render(<App/>);
